#!/bin/zsh
#
## ResolDL2-to-Domoticz

ResolDL2Host='YourResolDL2Host'
DomoticzHost='YourDomoticzHost'

curl=`which curl`

## Tweak IFS so that we separate on newline, not spaces
## Record the old value
OLDIFS="${IFS}"
## Tweak it
IFS=$'\n'

for SolarHWStat in $(
	${curl} -s "https://${ResolDL2Host}/dlx/download/download?source=current&outputType=text-csv-lf&filter=00" \
		| tail -n 2 \
		| cut -f1-8 -d';' \
		| sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/;/g' \
		| awk -F';' '{printf "\n"$2","$10"\n"$3","$11"\n"$4","$12"\n"$5","$13"\n"$6","$14"\n"$7","$15"\n"$8","$16"\n"}' \
		| sed -e 's/Solar Collector/IDX#,Solar Collector (°C)/' \
			-e 's/Hot-Water-Tank Bottom/IDX#,Hot-Water-Tank Bottom (°C)/' \
			-e 's/Hot-Water-Tank Top/IDX#,Hot-Water-Tank Top (°C)/' \
			-e 's/Pump-Station Return/IDX#,Pump-Station Return (°C)/' \
			-e 's/Pump Duty-Cycle/IDX#,Pump Duty-Cycle (%)/' \
			-e 's/Total Pumping Hours/IDX#,Total Pumping Hours/' \
			-e 's/Total kWh Heat-Generation/IDX#,Total kWh Heat-Generation/'
)
do
    echo -e -n "\e[1;4;35m"
    print "${SolarHWStat}"
    IDX=`echo ${SolarHWStat} | cut -f1 -d','`
    STAT=`echo ${SolarHWStat} | cut -f3 -d','`
    echo -e -n "\e[1;4;33m"
    echo ${curl} -s -X PUT "http://${DomoticzHost}/json.htm?type=command&param=udevice&idx=${IDX}&nvalue=0&svalue=${STAT}"
    echo -e -n "\e[0m"
    ${curl} -s -X PUT "http://${DomoticzHost}/json.htm?type=command&param=udevice&idx=${IDX}&nvalue=0&svalue=${STAT}"
done

## Return IFS to normal
IFS="${OLDIFS}"

exit 0

#EOF
